### ISSUE TITLE
SDK 3.10.5 - HttpClient

### ISSUE THREAD

**Issue by meeximum** [SAP/sap_mobile_platform_windows#1]
Hi Milton,

it seems that with the actual SDK following coding doesn't work anymore?

`var client = new SAP.Net.Http.HttpClient(
                                new System.Net.Http.HttpClientHandler()
                                {
                                    Credentials =
                                        new System.Net.NetworkCredential(
                                        Globals.LogonCore.LogonContext.RegistrationContext.BackendUserName,
                                        Globals.LogonCore.LogonContext.RegistrationContext.BackendPassword)
                                },
                                true); // will be disposed by the store!
                client.DefaultRequestHeaders.TryAddWithoutValidation("X-SMP-APPCID", connectionId);
                client.DefaultRequestHeaders.TryAddWithoutValidation("X-SUP-APPCID", connectionId);`

**Comment by meeximum** [comment]
When I implement the client without a filter! I got

   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeBufferExtensions.CopyTo(IBuffer source, UInt32 sourceIndex, Byte[] destination, Int32 destinationIndex, Int32 count)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeBufferExtensions.ToArray(IBuffer source, UInt32 sourceIndex, Int32 count)
   at System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeBufferExtensions.ToArray(IBuffer source)
   at SAP.Net.Extensions.HttpResponseMessageExtension.EnsureSuccessStatusCodeWithResponse(HttpResponseMessage response)
   at SAP.Data.OData.Online.Store.ODataStore.<OpenAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EggerCRM.Contexts.SapContext.<Init>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EggerCRM.ViewModels.MainViewModel.<ExecuteGetCustomersCommand>d__5.MoveNext()

**Comment by meeximum** [comment]
ok, Problem was, that I forgot to set the PasswordCredentials at the client
